language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tommasolevato/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tommasolevato/react-test npm test

after_success:
  - docker build -t tommasolevato/multi-client ./client
  - docker build -t tommasolevato/multi-nginx ./nginx
  - docker build -t tommasolevato/multi-server ./server
  - docker build -t tommasolevato/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tommasolevato/multi-client
  - docker push tommasolevato/multi-nginx
  - docker push tommasolevato/multi-server
  - docker push tommasolevato/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-eu-north-1-546419751747"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
