language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tommasolevato/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tommasolevato/react-test npm test

after_success:
  - docker build -t tommasolevato/multi-client -f ./client
  - docker build -t tommasolevato/multi-nginx -f ./nginx
  - docker build -t tommasolevato/multi-server -f ./server
  - docker build -t tommasolevato/multi-worker -f ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tommasolevato/multi-client
  - docker push tommasolevato/multi-nginx
  - docker push tommasolevato/multi-server
  - docker push tommasolevato/multi-worker
